name: Standalone 3.x Test CI

on:
  push:
    branches: [openmrs-emr3]
  pull_request:
    branches: [openmrs-emr3]

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: on Linux (Java 21)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Verify Docker Compose installation
        run: docker compose version

      - name: Pre-run OpenMRS SDK Plugin
        run: mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:setup-sdk -B --settings .github/maven-settings.xml

      - name: Run Maven Clean
        run: mvn clean --settings .github/maven-settings.xml

      - name: Run Maven Install
        run: mvn install --settings .github/maven-settings.xml

  build-windows:
    name: on Windows (Java 21)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Pre-run OpenMRS SDK Plugin
        run: mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:setup-sdk -B --settings .github/maven-settings.xml

      - name: Run Maven Clean
        run: mvn clean --settings .github/maven-settings.xml

      - name: Run Maven Install
        run: mvn install -Pci --settings .github/maven-settings.xml

  build-macos:
    name: on macOS (Java 21)
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Pre-run OpenMRS SDK Plugin
        run: mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:setup-sdk -B --settings .github/maven-settings.xml

      - name: Run Maven Clean
        run: mvn clean --settings .github/maven-settings.xml

      - name: Run Maven Install
        run: mvn install -Pci --settings .github/maven-settings.xml