name: Standalone 3.x Test CI

on:
  push:
    branches: [openmrs-emr3]
  pull_request:
    branches: [openmrs-emr3]

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: on Linux (Java 21)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Maven Clean
        run: mvn clean

      - name: Run Maven Install
        run: mvn install

  build-windows:
    name: on Windows (Java 21)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Maven Clean
        run: mvn clean

      - name: Run Maven Install
        run: mvn install

  build-macos:
    name: on macOS (Java 21)
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Maven Clean
        run: mvn clean

      - name: Run Maven Install
        run: mvn install