name: Standalone 3.x Test CI

on:
  push:
    branches: [openmrs-emr3]
  pull_request:
    branches: [openmrs-emr3]

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: on Linux (Java 21)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Verify Docker Compose installation
        run: docker compose version

      - name: Run Maven Clean
        run: mvn clean --settings .github/maven-settings.xml

      - name: Run Maven Install
        run: mvn install --settings .github/maven-settings.xml

  build-windows:
    name: on Windows (Java 21)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download Docker Compose
        shell: powershell
        run: |
          $composeVersion = "v2.24.5"
          $downloadUrl = "https://github.com/docker/compose/releases/download/$composeVersion/docker-compose-windows-x86_64.exe"
          $destinationDir = "$Env:ProgramFiles\Docker"
          $destinationPath = "$destinationDir\docker-compose.exe"
          
          # Create the destination directory if it doesn't exist
          if (!(Test-Path -Path $destinationDir)) {
            New-Item -ItemType Directory -Force -Path $destinationDir | Out-Null
          }
          
          # Download Docker Compose
          Invoke-WebRequest -Uri $downloadUrl -OutFile $destinationPath

      - name: Verify Docker Compose Installation
        shell: powershell
        run: docker-compose.exe --version

      - name: Run Maven Clean
        run: mvn clean --settings .github/maven-settings.xml

      - name: Run Maven Install
        run: mvn install --settings .github/maven-settings.xml

  build-macos:
    name: on macOS (Java 21)
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Docker Compose
        run: |
          brew install docker docker-compose
          docker-compose --version     

      - name: Run Maven Clean
        run: mvn clean --settings .github/maven-settings.xml

      - name: Run Maven Install
        run: mvn install --settings .github/maven-settings.xml